version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./target/custom-authenticator.jar:/opt/keycloak/providers/custom-authenticator.jar:ro
      - keycloak_data:/opt/keycloak/data
    command: ["start-dev", "--http-port=8080"]

volumes:
  keycloak_data:

